name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  #container-job:
  #  runs-on: ubuntu-20.04

  #container:
  #  image: wordpress:cli

  #services:
  #  mysql:
  #    image: mysql:5.7

  try-host-mysql:
    runs-on: ubuntu-20.04

    steps:
      - name: Start MySQL server
        run: |
          sudo systemctl status mysql.service || :
          sudo systemctl start mysql.service
          #echo -e "[client]\nuser=root\npassword=root" > ~/.my.cnf
          #chmod 0600 ~/.my.cnf
          echo root | mysql_config_editor set --login-path=client --host=localhost --user=root --password
          mysql_config_editor print --all

      - run: mysql -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;" || true

