name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  #container-job:
  #  runs-on: ubuntu-20.04

  #container:
  #  image: wordpress:cli

  #services:
  #  mysql:
  #    image: mysql:5.7

  try-host-mysql:
    runs-on: ubuntu-20.04

    steps:
      - name: Start MySQL server
        run: |
          sudo systemctl status mysql.service || :
          sudo systemctl start mysql.service
          echo root | mysql_config_editor set --login-path=client --host=localhost --user=root --password
          mysql_config_editor print --all

      - run: mysql -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;" || true

      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      - run: |
          php wp-cli.phar --info
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp --info

      - run: wp core download
      - run: |
          wp core config --dbname=riskprofiler --dbuser=root --dbpass=root --dbhost=localhost --dbprefix=whebfubwef_ --extra-php <<PHP
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          PHP
      - run: wp db create
      - run: wp core install --url=https://riskprofiler.ca --title=RiskProfiler.ca --admin_user=username --admin_password=mypassword --admin_email=my@email.com
      - run: wp plugin list

      # https://docs.wp2static.com/en/getting-started/installation/#via-cli
      #- run: wp plugin install static-html-output-plugin --activate

      # outdated?
      - run: wp plugin install simply-static --activate

      # https://grrr.tech/posts/2020/wordpress-static-site-generator-and-deployment-via-simply-static-deploy/
      - run: sudo eatmydata apt-get update
      - run: sudo eatmydata apt-get install composer
      - run: mkdir webb
      - run: pwd
      - run: |
          cd webb
          pwd
      - run: pwd
