name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  #container-job:
  #  runs-on: ubuntu-20.04

  #container:
  #  image: wordpress:cli

  #services:
  #  mysql:
  #    image: mysql:5.7

  try-host-mysql:
    runs-on: ubuntu-20.04

    steps:
      - run: which mysql
      - run: mysql --version
      - run: sudo systemctl status mysql.service || :
      - run: sudo systemctl start mysql.service
      - run: sudo systemctl status mysql.service || :
      - run: sleep 1
      - run: sudo systemctl status mysql.service || :
      - run: sleep 1
      - run: sudo systemctl status mysql.service || :
      - run: ps auxwww | grep -i sql
      - run: mysql -u root -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;"
