name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  #container-job:
  #  runs-on: ubuntu-20.04

  #container:
  #  image: wordpress:cli

  #services:
  #  mysql:
  #    image: mysql:5.7

  try-host-mysql:
    runs-on: ubuntu-20.04

    steps:
      - run: which mysql
      - run: mysql --version
      - run: sudo systemctl status mysql.service || true
      - run: sudo systemctl start mysql.service
      - run: sudo systemctl status mysql.service || true
      - run: cat /etc/mysql/my.cnf
      - run: mysql -uroot -p -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'
      - run: mysql -u root -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;"
