name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  #container-job:
  #  runs-on: ubuntu-20.04

  #container:
  #  image: wordpress:cli

  #services:
  #  mysql:
  #    image: mysql:5.7

  try-host-mysql:
    runs-on: ubuntu-20.04

    steps:
      - run: which mysql
      - run: mysql --version
      - run: sudo systemctl status mysql.service || true
      - run: sudo systemctl start mysql.service
      - run: sudo systemctl status mysql.service || true
      - run: cat /etc/mysql/my.cnf
      - run: /usr/bin/mysql -u root -D mysql -e "update user set password=password('new-password') where user='root'"
      - run: /usr/bin/mysql -u root -e "flush privileges"
      - run: mysql -u root -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;"
